version: '3.1'
services:
  nginx:
    restart: always
    image: nginx:mainline-alpine
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    ports:
      - "8231:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  geoserver:
    image: geoserver:2.16.1
    build:
      context: ./geoserver/2.16.1
      args:
        - TOMCAT_EXTRAS=false
    restart: always
    logging:
        driver: "json-file"
        options:
          max-size: "10m"
          max-file: "10"
    volumes:
      - ./geoserver/geoserver_data:/opt/geoserver/data_dir
      - ./geoserver/tomcat_settings/setenv.sh:/usr/local/tomcat/bin/setenv.sh
      - ./geoserver/logs:/usr/local/tomcat/logs
    healthcheck:
      test: curl --fail -s http://localhost:8080/geoserver || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
  postgis:
    image: kartoza/postgis:11.0-2.5
    volumes:
      - ./postgis/data:/var/lib/postgresql
    ports:
      - "8232:5432"
    environment:
      - USERNAME=avatar
      - PASS=HcLgFb#KNCGlpg8X
      - ALLOW_IP_RANGE=0.0.0.0/0
    restart: on-failure
    healthcheck:
      test: "exit 0"
volumes:
  pgadmin-data:
